# Docker Compose configuration for parallel E2E testing
# Orchestrates multiple testing agents, each running a section of the test plan

version: '3.8'

services:
  # Shared Qdrant instance for all agents
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/6333' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # Agent 1: Installation & Setup Tests
  agent-install:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-install
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-install
      - TEST_SECTION=installation
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_install_results:/test_results
      - agent_install_logs:/test_logs
    command: ["--section", "installation"]

  # Agent 2: MCP Tools Tests (Part 1 - Memory Management)
  agent-mcp-memory:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-mcp-memory
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-mcp-memory
      - TEST_SECTION=mcp-memory
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_mcp_memory_results:/test_results
      - agent_mcp_memory_logs:/test_logs
    command: ["--section", "mcp-memory"]

  # Agent 3: MCP Tools Tests (Part 2 - Code Intelligence)
  agent-mcp-code:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-mcp-code
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-mcp-code
      - TEST_SECTION=mcp-code
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_mcp_code_results:/test_results
      - agent_mcp_code_logs:/test_logs
    command: ["--section", "mcp-code"]

  # Agent 4: MCP Tools Tests (Part 3 - Multi-Project & Monitoring)
  agent-mcp-advanced:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-mcp-advanced
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-mcp-advanced
      - TEST_SECTION=mcp-advanced
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_mcp_advanced_results:/test_results
      - agent_mcp_advanced_logs:/test_logs
    command: ["--section", "mcp-advanced"]

  # Agent 5: CLI Commands Tests (Part 1 - Core)
  agent-cli-core:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-cli-core
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-cli-core
      - TEST_SECTION=cli-core
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_cli_core_results:/test_results
      - agent_cli_core_logs:/test_logs
    command: ["--section", "cli-core"]

  # Agent 6: CLI Commands Tests (Part 2 - Management)
  agent-cli-management:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-cli-management
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-cli-management
      - TEST_SECTION=cli-management
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_cli_management_results:/test_results
      - agent_cli_management_logs:/test_logs
    command: ["--section", "cli-management"]

  # Agent 7: Code Search & Indexing Tests
  agent-code-search:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-code-search
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-code-search
      - TEST_SECTION=code-search
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_code_search_results:/test_results
      - agent_code_search_logs:/test_logs
    command: ["--section", "code-search"]

  # Agent 8: Memory, Multi-Project, Health Tests
  agent-features:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-features
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-features
      - TEST_SECTION=features
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_features_results:/test_results
      - agent_features_logs:/test_logs
    command: ["--section", "features"]

  # Agent 9: Dashboard, Configuration, Security Tests
  agent-ui-config:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-ui-config
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-ui-config
      - TEST_SECTION=ui-config
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_ui_config_results:/test_results
      - agent_ui_config_logs:/test_logs
    command: ["--section", "ui-config"]

  # Agent 10: Performance, Error Handling, UX Tests
  agent-quality:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-agent-quality
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - AGENT_ID=agent-quality
      - TEST_SECTION=quality
      - QDRANT_HOST=qdrant
      - CLAUDE_RAG_QDRANT_URL=http://qdrant:6333
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_quality_results:/test_results
      - agent_quality_logs:/test_logs
    command: ["--section", "quality"]

  # Orchestrator - Coordinates agents and aggregates results
  orchestrator:
    build:
      context: ..
      dockerfile: planning_docs/TEST-006_docker_agent_minimal.Dockerfile
    container_name: e2e-orchestrator
    depends_on:
      - agent-install
      - agent-mcp-memory
      - agent-mcp-code
      - agent-mcp-advanced
      - agent-cli-core
      - agent-cli-management
      - agent-code-search
      - agent-features
      - agent-ui-config
      - agent-quality
    volumes:
      - ./TEST-006_test_assignments.json:/app/test_assignments.json:ro
      - agent_install_results:/results/agent-install:ro
      - agent_mcp_memory_results:/results/agent-mcp-memory:ro
      - agent_mcp_code_results:/results/agent-mcp-code:ro
      - agent_mcp_advanced_results:/results/agent-mcp-advanced:ro
      - agent_cli_core_results:/results/agent-cli-core:ro
      - agent_cli_management_results:/results/agent-cli-management:ro
      - agent_code_search_results:/results/agent-code-search:ro
      - agent_features_results:/results/agent-features:ro
      - agent_ui_config_results:/results/agent-ui-config:ro
      - agent_quality_results:/results/agent-quality:ro
      - ./results:/final_results
    command: ["python", "-m", "testing.orchestrator.coordinator", "--aggregate"]

volumes:
  qdrant_storage:
  agent_install_results:
  agent_mcp_memory_results:
  agent_mcp_code_results:
  agent_mcp_advanced_results:
  agent_cli_core_results:
  agent_cli_management_results:
  agent_code_search_results:
  agent_features_results:
  agent_ui_config_results:
  agent_quality_results:
  agent_install_logs:
  agent_mcp_memory_logs:
  agent_mcp_code_logs:
  agent_mcp_advanced_logs:
  agent_cli_core_logs:
  agent_cli_management_logs:
  agent_code_search_logs:
  agent_features_logs:
  agent_ui_config_logs:
  agent_quality_logs:

networks:
  default:
    name: e2e-testing-network
